name: Reader
options:
  bundleIdPrefix: com.kurt
  deploymentTarget:
    macOS: '14.0'
configs:
  Debug: debug
  Release: release
settings:
  base:
    PRODUCT_NAME: Reader
    SWIFT_VERSION: '5.10'

targets:
  Reader:
    type: application
    platform: macOS
    sources:
      - path: App
      - path: Features
      - path: Core
      - path: Core/Storage/FileStore/LibraryCatalogStore.swift
      - path: Core/Storage/FileStore/ReadingProgressStore.swift
      - path: Infrastructure
      - path: Resources/Assets.xcassets
        buildPhase: resources
      - path: Resources/Fonts
        buildPhase: resources
      - path: Resources/Localizable
        buildPhase: resources
      - path: Resources/SampleBooks
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kurt.reader
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleIconName: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        ARCHS: arm64
    scheme:
      testTargets:
        - ReaderUnitTests
        - ReaderUITests

  ReaderUnitTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/UnitTests
    dependencies:
      - target: Reader
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kurt.reader.unittests
        GENERATE_INFOPLIST_FILE: YES

  ReaderUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: Tests/UITests
    dependencies:
      - target: Reader
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kurt.reader.uitests
        GENERATE_INFOPLIST_FILE: YES
